'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Represents a strongly typed in-memory cache of data.
'''</summary>
<Global.System.Serializable(),  _
 Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
 Global.System.ComponentModel.ToolboxItem(true),  _
 Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 Global.System.Xml.Serialization.XmlRootAttribute("Labels"),  _
 Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class Labels
    Inherits Global.System.Data.DataSet
    
    Private tabledtLabels As dtLabelsDataTable
    
    Private _schemaSerializationMode As Global.System.Data.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
    
  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
  Public Sub New()
    MyBase.New()
    Me.BeginInit()
    Me.InitClass()
    Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
    AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
    AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
    Me.EndInit()
  End Sub

  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
  Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
    MyBase.New(info, context, False)
    If (Me.IsBinarySerialized(info, context) = True) Then
      Me.InitVars(False)
      Dim schemaChangedHandler1 As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
      AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
      AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
      Return
    End If
    Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)), String)
    If (Me.DetermineSchemaSerializationMode(info, context) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
      Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet()
      ds.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
      If (Not (ds.Tables("dtLabels")) Is Nothing) Then
        MyBase.Tables.Add(New dtLabelsDataTable(ds.Tables("dtLabels")))
      End If
      Me.DataSetName = ds.DataSetName
      Me.Prefix = ds.Prefix
      Me.Namespace = ds.Namespace
      Me.Locale = ds.Locale
      Me.CaseSensitive = ds.CaseSensitive
      Me.EnforceConstraints = ds.EnforceConstraints
      Me.Merge(ds, False, Global.System.Data.MissingSchemaAction.Add)
      Me.InitVars()
    Else
      Me.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
    End If
    Me.GetSerializationData(info, context)
    Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
    AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
    AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
  End Sub

  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"), _
   Global.System.ComponentModel.Browsable(False), _
   Global.System.ComponentModel.DesignerSerializationVisibility(Global.System.ComponentModel.DesignerSerializationVisibility.Content)> _
  Public ReadOnly Property dtLabels() As dtLabelsDataTable
    Get
      Return Me.tabledtLabels
    End Get
  End Property

  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"), _
   Global.System.ComponentModel.BrowsableAttribute(True), _
   Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Visible)> _
  Public Overrides Property SchemaSerializationMode() As Global.System.Data.SchemaSerializationMode
    Get
      Return Me._schemaSerializationMode
    End Get
    Set(value As Global.System.Data.SchemaSerializationMode)
      Me._schemaSerializationMode = value
    End Set
  End Property

  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"), _
   Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)> _
  Public Shadows ReadOnly Property Tables() As Global.System.Data.DataTableCollection
    Get
      Return MyBase.Tables
    End Get
  End Property

  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"), _
   Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)> _
  Public Shadows ReadOnly Property Relations() As Global.System.Data.DataRelationCollection
    Get
      Return MyBase.Relations
    End Get
  End Property

  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
  Protected Overrides Sub InitializeDerivedDataSet()
    Me.BeginInit()
    Me.InitClass()
    Me.EndInit()
  End Sub

  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
  Public Overrides Function Clone() As Global.System.Data.DataSet
    Dim cln As Labels = CType(MyBase.Clone, Labels)
    cln.InitVars()
    cln.SchemaSerializationMode = Me.SchemaSerializationMode
    Return cln
  End Function

  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
  Protected Overrides Function ShouldSerializeTables() As Boolean
    Return False
  End Function

  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
  Protected Overrides Function ShouldSerializeRelations() As Boolean
    Return False
  End Function

  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
  Protected Overrides Sub ReadXmlSerializable(ByVal reader As Global.System.Xml.XmlReader)
    If (Me.DetermineSchemaSerializationMode(reader) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
      Me.Reset()
      Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet()
      ds.ReadXml(reader)
      If (Not (ds.Tables("dtLabels")) Is Nothing) Then
        MyBase.Tables.Add(New dtLabelsDataTable(ds.Tables("dtLabels")))
      End If
      Me.DataSetName = ds.DataSetName
      Me.Prefix = ds.Prefix
      Me.Namespace = ds.Namespace
      Me.Locale = ds.Locale
      Me.CaseSensitive = ds.CaseSensitive
      Me.EnforceConstraints = ds.EnforceConstraints
      Me.Merge(ds, False, Global.System.Data.MissingSchemaAction.Add)
      Me.InitVars()
    Else
      Me.ReadXml(reader)
      Me.InitVars()
    End If
  End Sub

  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
  Protected Overrides Function GetSchemaSerializable() As Global.System.Xml.Schema.XmlSchema
    Dim stream As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
    Me.WriteXmlSchema(New Global.System.Xml.XmlTextWriter(stream, Nothing))
    stream.Position = 0
    Return Global.System.Xml.Schema.XmlSchema.Read(New Global.System.Xml.XmlTextReader(stream), Nothing)
  End Function

  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
  Friend Overloads Sub InitVars()
    Me.InitVars(True)
  End Sub

  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
  Friend Overloads Sub InitVars(ByVal initTable As Boolean)
    Me.tabledtLabels = CType(MyBase.Tables("dtLabels"), dtLabelsDataTable)
    If (initTable = True) Then
      If (Not (Me.tabledtLabels) Is Nothing) Then
        Me.tabledtLabels.InitVars()
      End If
    End If
  End Sub

  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
  Private Sub InitClass()
    Me.DataSetName = "Labels"
    Me.Prefix = ""
    Me.Namespace = "http://tempuri.org/Labels.xsd"
    Me.EnforceConstraints = True
    Me.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
    Me.tabledtLabels = New dtLabelsDataTable()
    MyBase.Tables.Add(Me.tabledtLabels)
  End Sub

  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
  Private Function ShouldSerializedtLabels() As Boolean
    Return False
  End Function

  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
  Private Sub SchemaChanged(ByVal sender As Object, ByVal e As Global.System.ComponentModel.CollectionChangeEventArgs)
    If (e.Action = Global.System.ComponentModel.CollectionChangeAction.Remove) Then
      Me.InitVars()
    End If
  End Sub

  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
  Public Shared Function GetTypedDataSetSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
    Dim ds As Labels = New Labels()
    Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType()
    Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence()
    Dim any As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
    any.Namespace = ds.Namespace
    sequence.Items.Add(any)
    type.Particle = sequence
    Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
    If xs.Contains(dsSchema.TargetNamespace) Then
      Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
      Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
      Try
        Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
        dsSchema.Write(s1)
        Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
        Do While schemas.MoveNext
          schema = CType(schemas.Current, Global.System.Xml.Schema.XmlSchema)
          s2.SetLength(0)
          schema.Write(s2)
          If (s1.Length = s2.Length) Then
            s1.Position = 0
            s2.Position = 0

            Do While ((s1.Position <> s1.Length) _
                        AndAlso (s1.ReadByte = s2.ReadByte))


            Loop
            If (s1.Position = s1.Length) Then
              Return type
            End If
          End If

        Loop
      Finally
        If (Not (s1) Is Nothing) Then
          s1.Close()
        End If
        If (Not (s2) Is Nothing) Then
          s2.Close()
        End If
      End Try
    End If
    xs.Add(dsSchema)
    Return type
  End Function

  <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
  Public Delegate Sub dtLabelsRowChangeEventHandler(ByVal sender As Object, ByVal e As dtLabelsRowChangeEvent)

  '''<summary>
  '''Represents the strongly named DataTable class.
  '''</summary>
  <Global.System.Serializable(), _
   Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")> _
  Partial Public Class dtLabelsDataTable
    Inherits Global.System.Data.TypedTableBase(Of dtLabelsRow)

    Private columnPurchaseID As Global.System.Data.DataColumn

    Private columnQty As Global.System.Data.DataColumn

    Private columnBarcode As Global.System.Data.DataColumn

    Private columnSalePrice As Global.System.Data.DataColumn

    Private columnModelName As Global.System.Data.DataColumn

    Private columnSizeTitle As Global.System.Data.DataColumn

    Private columnColorName As Global.System.Data.DataColumn

    Private columnSalePercentage As Global.System.Data.DataColumn

    Private columnCompanyName As Global.System.Data.DataColumn

    Private columnBarcodeImage As Global.System.Data.DataColumn

    Private columnRecID As Global.System.Data.DataColumn

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Sub New()
      MyBase.New()
      Me.TableName = "dtLabels"
      Me.BeginInit()
      Me.InitClass()
      Me.EndInit()
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Friend Sub New(ByVal table As Global.System.Data.DataTable)
      MyBase.New()
      Me.TableName = table.TableName
      If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
        Me.CaseSensitive = table.CaseSensitive
      End If
      If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
        Me.Locale = table.Locale
      End If
      If (table.Namespace <> table.DataSet.Namespace) Then
        Me.Namespace = table.Namespace
      End If
      Me.Prefix = table.Prefix
      Me.MinimumCapacity = table.MinimumCapacity
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
      MyBase.New(info, context)
      Me.InitVars()
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public ReadOnly Property PurchaseIDColumn() As Global.System.Data.DataColumn
      Get
        Return Me.columnPurchaseID
      End Get
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public ReadOnly Property QtyColumn() As Global.System.Data.DataColumn
      Get
        Return Me.columnQty
      End Get
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public ReadOnly Property BarcodeColumn() As Global.System.Data.DataColumn
      Get
        Return Me.columnBarcode
      End Get
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public ReadOnly Property SalePriceColumn() As Global.System.Data.DataColumn
      Get
        Return Me.columnSalePrice
      End Get
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public ReadOnly Property ModelNameColumn() As Global.System.Data.DataColumn
      Get
        Return Me.columnModelName
      End Get
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public ReadOnly Property SizeTitleColumn() As Global.System.Data.DataColumn
      Get
        Return Me.columnSizeTitle
      End Get
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public ReadOnly Property ColorNameColumn() As Global.System.Data.DataColumn
      Get
        Return Me.columnColorName
      End Get
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public ReadOnly Property SalePercentageColumn() As Global.System.Data.DataColumn
      Get
        Return Me.columnSalePercentage
      End Get
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public ReadOnly Property CompanyNameColumn() As Global.System.Data.DataColumn
      Get
        Return Me.columnCompanyName
      End Get
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public ReadOnly Property BarcodeImageColumn() As Global.System.Data.DataColumn
      Get
        Return Me.columnBarcodeImage
      End Get
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public ReadOnly Property RecIDColumn() As Global.System.Data.DataColumn
      Get
        Return Me.columnRecID
      End Get
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"), _
     Global.System.ComponentModel.Browsable(False)> _
    Public ReadOnly Property Count() As Integer
      Get
        Return Me.Rows.Count
      End Get
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Default Public ReadOnly Property Item(ByVal index As Integer) As dtLabelsRow
      Get
        Return CType(Me.Rows(index), dtLabelsRow)
      End Get
    End Property

    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Event dtLabelsRowChanging As dtLabelsRowChangeEventHandler

    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Event dtLabelsRowChanged As dtLabelsRowChangeEventHandler

    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Event dtLabelsRowDeleting As dtLabelsRowChangeEventHandler

    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Event dtLabelsRowDeleted As dtLabelsRowChangeEventHandler

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Overloads Sub AdddtLabelsRow(ByVal row As dtLabelsRow)
      Me.Rows.Add(row)
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Overloads Function AdddtLabelsRow(ByVal PurchaseID As Integer, ByVal Qty As Integer, ByVal Barcode As String, ByVal SalePrice As Integer, ByVal ModelName As String, ByVal SizeTitle As String, ByVal ColorName As String, ByVal SalePercentage As Integer, ByVal CompanyName As String, ByVal BarcodeImage() As Byte, ByVal RecID As Integer) As dtLabelsRow
      Dim rowdtLabelsRow As dtLabelsRow = CType(Me.NewRow, dtLabelsRow)
      Dim columnValuesArray() As Object = New Object() {PurchaseID, Qty, Barcode, SalePrice, ModelName, SizeTitle, ColorName, SalePercentage, CompanyName, BarcodeImage, RecID}
      rowdtLabelsRow.ItemArray = columnValuesArray
      Me.Rows.Add(rowdtLabelsRow)
      Return rowdtLabelsRow
    End Function

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Overrides Function Clone() As Global.System.Data.DataTable
      Dim cln As dtLabelsDataTable = CType(MyBase.Clone, dtLabelsDataTable)
      cln.InitVars()
      Return cln
    End Function

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Protected Overrides Function CreateInstance() As Global.System.Data.DataTable
      Return New dtLabelsDataTable()
    End Function

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Friend Sub InitVars()
      Me.columnPurchaseID = MyBase.Columns("PurchaseID")
      Me.columnQty = MyBase.Columns("Qty")
      Me.columnBarcode = MyBase.Columns("Barcode")
      Me.columnSalePrice = MyBase.Columns("SalePrice")
      Me.columnModelName = MyBase.Columns("ModelName")
      Me.columnSizeTitle = MyBase.Columns("SizeTitle")
      Me.columnColorName = MyBase.Columns("ColorName")
      Me.columnSalePercentage = MyBase.Columns("SalePercentage")
      Me.columnCompanyName = MyBase.Columns("CompanyName")
      Me.columnBarcodeImage = MyBase.Columns("BarcodeImage")
      Me.columnRecID = MyBase.Columns("RecID")
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Private Sub InitClass()
      Me.columnPurchaseID = New Global.System.Data.DataColumn("PurchaseID", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
      MyBase.Columns.Add(Me.columnPurchaseID)
      Me.columnQty = New Global.System.Data.DataColumn("Qty", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
      MyBase.Columns.Add(Me.columnQty)
      Me.columnBarcode = New Global.System.Data.DataColumn("Barcode", GetType(String), Nothing, Global.System.Data.MappingType.Element)
      MyBase.Columns.Add(Me.columnBarcode)
      Me.columnSalePrice = New Global.System.Data.DataColumn("SalePrice", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
      MyBase.Columns.Add(Me.columnSalePrice)
      Me.columnModelName = New Global.System.Data.DataColumn("ModelName", GetType(String), Nothing, Global.System.Data.MappingType.Element)
      MyBase.Columns.Add(Me.columnModelName)
      Me.columnSizeTitle = New Global.System.Data.DataColumn("SizeTitle", GetType(String), Nothing, Global.System.Data.MappingType.Element)
      MyBase.Columns.Add(Me.columnSizeTitle)
      Me.columnColorName = New Global.System.Data.DataColumn("ColorName", GetType(String), Nothing, Global.System.Data.MappingType.Element)
      MyBase.Columns.Add(Me.columnColorName)
      Me.columnSalePercentage = New Global.System.Data.DataColumn("SalePercentage", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
      MyBase.Columns.Add(Me.columnSalePercentage)
      Me.columnCompanyName = New Global.System.Data.DataColumn("CompanyName", GetType(String), Nothing, Global.System.Data.MappingType.Element)
      MyBase.Columns.Add(Me.columnCompanyName)
      Me.columnBarcodeImage = New Global.System.Data.DataColumn("BarcodeImage", GetType(Byte()), Nothing, Global.System.Data.MappingType.Element)
      MyBase.Columns.Add(Me.columnBarcodeImage)
      Me.columnRecID = New Global.System.Data.DataColumn("RecID", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
      MyBase.Columns.Add(Me.columnRecID)
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Function NewdtLabelsRow() As dtLabelsRow
      Return CType(Me.NewRow, dtLabelsRow)
    End Function

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Protected Overrides Function NewRowFromBuilder(ByVal builder As Global.System.Data.DataRowBuilder) As Global.System.Data.DataRow
      Return New dtLabelsRow(builder)
    End Function

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Protected Overrides Function GetRowType() As Global.System.Type
      Return GetType(dtLabelsRow)
    End Function

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Protected Overrides Sub OnRowChanged(ByVal e As Global.System.Data.DataRowChangeEventArgs)
      MyBase.OnRowChanged(e)
      If (Not (Me.dtLabelsRowChangedEvent) Is Nothing) Then
        RaiseEvent dtLabelsRowChanged(Me, New dtLabelsRowChangeEvent(CType(e.Row, dtLabelsRow), e.Action))
      End If
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Protected Overrides Sub OnRowChanging(ByVal e As Global.System.Data.DataRowChangeEventArgs)
      MyBase.OnRowChanging(e)
      If (Not (Me.dtLabelsRowChangingEvent) Is Nothing) Then
        RaiseEvent dtLabelsRowChanging(Me, New dtLabelsRowChangeEvent(CType(e.Row, dtLabelsRow), e.Action))
      End If
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Protected Overrides Sub OnRowDeleted(ByVal e As Global.System.Data.DataRowChangeEventArgs)
      MyBase.OnRowDeleted(e)
      If (Not (Me.dtLabelsRowDeletedEvent) Is Nothing) Then
        RaiseEvent dtLabelsRowDeleted(Me, New dtLabelsRowChangeEvent(CType(e.Row, dtLabelsRow), e.Action))
      End If
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Protected Overrides Sub OnRowDeleting(ByVal e As Global.System.Data.DataRowChangeEventArgs)
      MyBase.OnRowDeleting(e)
      If (Not (Me.dtLabelsRowDeletingEvent) Is Nothing) Then
        RaiseEvent dtLabelsRowDeleting(Me, New dtLabelsRowChangeEvent(CType(e.Row, dtLabelsRow), e.Action))
      End If
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Sub RemovedtLabelsRow(ByVal row As dtLabelsRow)
      Me.Rows.Remove(row)
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Shared Function GetTypedTableSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
      Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType()
      Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence()
      Dim ds As Labels = New Labels()
      Dim any1 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
      any1.Namespace = "http://www.w3.org/2001/XMLSchema"
      any1.MinOccurs = New Decimal(0)
      any1.MaxOccurs = Decimal.MaxValue
      any1.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
      sequence.Items.Add(any1)
      Dim any2 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
      any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
      any2.MinOccurs = New Decimal(1)
      any2.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
      sequence.Items.Add(any2)
      Dim attribute1 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute()
      attribute1.Name = "namespace"
      attribute1.FixedValue = ds.Namespace
      type.Attributes.Add(attribute1)
      Dim attribute2 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute()
      attribute2.Name = "tableTypeName"
      attribute2.FixedValue = "dtLabelsDataTable"
      type.Attributes.Add(attribute2)
      type.Particle = sequence
      Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
      If xs.Contains(dsSchema.TargetNamespace) Then
        Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
        Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
        Try
          Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
          dsSchema.Write(s1)
          Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
          Do While schemas.MoveNext
            schema = CType(schemas.Current, Global.System.Xml.Schema.XmlSchema)
            s2.SetLength(0)
            schema.Write(s2)
            If (s1.Length = s2.Length) Then
              s1.Position = 0
              s2.Position = 0

              Do While ((s1.Position <> s1.Length) _
                          AndAlso (s1.ReadByte = s2.ReadByte))


              Loop
              If (s1.Position = s1.Length) Then
                Return type
              End If
            End If

          Loop
        Finally
          If (Not (s1) Is Nothing) Then
            s1.Close()
          End If
          If (Not (s2) Is Nothing) Then
            s2.Close()
          End If
        End Try
      End If
      xs.Add(dsSchema)
      Return type
    End Function
  End Class

  '''<summary>
  '''Represents strongly named DataRow class.
  '''</summary>
  Partial Public Class dtLabelsRow
    Inherits Global.System.Data.DataRow

    Private tabledtLabels As dtLabelsDataTable

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Friend Sub New(ByVal rb As Global.System.Data.DataRowBuilder)
      MyBase.New(rb)
      Me.tabledtLabels = CType(Me.Table, dtLabelsDataTable)
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Property PurchaseID() As Integer
      Get
        Try
          Return CType(Me(Me.tabledtLabels.PurchaseIDColumn), Integer)
        Catch e As Global.System.InvalidCastException
          Throw New Global.System.Data.StrongTypingException("The value for column 'PurchaseID' in table 'dtLabels' is DBNull.", e)
        End Try
      End Get
      Set(value As Integer)
        Me(Me.tabledtLabels.PurchaseIDColumn) = value
      End Set
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Property Qty() As Integer
      Get
        Try
          Return CType(Me(Me.tabledtLabels.QtyColumn), Integer)
        Catch e As Global.System.InvalidCastException
          Throw New Global.System.Data.StrongTypingException("The value for column 'Qty' in table 'dtLabels' is DBNull.", e)
        End Try
      End Get
      Set(value As Integer)
        Me(Me.tabledtLabels.QtyColumn) = value
      End Set
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Property Barcode() As String
      Get
        Try
          Return CType(Me(Me.tabledtLabels.BarcodeColumn), String)
        Catch e As Global.System.InvalidCastException
          Throw New Global.System.Data.StrongTypingException("The value for column 'Barcode' in table 'dtLabels' is DBNull.", e)
        End Try
      End Get
      Set(value As String)
        Me(Me.tabledtLabels.BarcodeColumn) = value
      End Set
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Property SalePrice() As Integer
      Get
        Try
          Return CType(Me(Me.tabledtLabels.SalePriceColumn), Integer)
        Catch e As Global.System.InvalidCastException
          Throw New Global.System.Data.StrongTypingException("The value for column 'SalePrice' in table 'dtLabels' is DBNull.", e)
        End Try
      End Get
      Set(value As Integer)
        Me(Me.tabledtLabels.SalePriceColumn) = value
      End Set
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Property ModelName() As String
      Get
        Try
          Return CType(Me(Me.tabledtLabels.ModelNameColumn), String)
        Catch e As Global.System.InvalidCastException
          Throw New Global.System.Data.StrongTypingException("The value for column 'ModelName' in table 'dtLabels' is DBNull.", e)
        End Try
      End Get
      Set(value As String)
        Me(Me.tabledtLabels.ModelNameColumn) = value
      End Set
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Property SizeTitle() As String
      Get
        Try
          Return CType(Me(Me.tabledtLabels.SizeTitleColumn), String)
        Catch e As Global.System.InvalidCastException
          Throw New Global.System.Data.StrongTypingException("The value for column 'SizeTitle' in table 'dtLabels' is DBNull.", e)
        End Try
      End Get
      Set(value As String)
        Me(Me.tabledtLabels.SizeTitleColumn) = value
      End Set
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Property ColorName() As String
      Get
        Try
          Return CType(Me(Me.tabledtLabels.ColorNameColumn), String)
        Catch e As Global.System.InvalidCastException
          Throw New Global.System.Data.StrongTypingException("The value for column 'ColorName' in table 'dtLabels' is DBNull.", e)
        End Try
      End Get
      Set(value As String)
        Me(Me.tabledtLabels.ColorNameColumn) = value
      End Set
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Property SalePercentage() As Integer
      Get
        Try
          Return CType(Me(Me.tabledtLabels.SalePercentageColumn), Integer)
        Catch e As Global.System.InvalidCastException
          Throw New Global.System.Data.StrongTypingException("The value for column 'SalePercentage' in table 'dtLabels' is DBNull.", e)
        End Try
      End Get
      Set(value As Integer)
        Me(Me.tabledtLabels.SalePercentageColumn) = value
      End Set
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Property CompanyName() As String
      Get
        Try
          Return CType(Me(Me.tabledtLabels.CompanyNameColumn), String)
        Catch e As Global.System.InvalidCastException
          Throw New Global.System.Data.StrongTypingException("The value for column 'CompanyName' in table 'dtLabels' is DBNull.", e)
        End Try
      End Get
      Set(value As String)
        Me(Me.tabledtLabels.CompanyNameColumn) = value
      End Set
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Property BarcodeImage() As Byte()
      Get
        Try
          Return CType(Me(Me.tabledtLabels.BarcodeImageColumn), Byte())
        Catch e As Global.System.InvalidCastException
          Throw New Global.System.Data.StrongTypingException("The value for column 'BarcodeImage' in table 'dtLabels' is DBNull.", e)
        End Try
      End Get
      Set(value As Byte())
        Me(Me.tabledtLabels.BarcodeImageColumn) = value
      End Set
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Property RecID() As Integer
      Get
        Try
          Return CType(Me(Me.tabledtLabels.RecIDColumn), Integer)
        Catch e As Global.System.InvalidCastException
          Throw New Global.System.Data.StrongTypingException("The value for column 'RecID' in table 'dtLabels' is DBNull.", e)
        End Try
      End Get
      Set(value As Integer)
        Me(Me.tabledtLabels.RecIDColumn) = value
      End Set
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Function IsPurchaseIDNull() As Boolean
      Return Me.IsNull(Me.tabledtLabels.PurchaseIDColumn)
    End Function

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Sub SetPurchaseIDNull()
      Me(Me.tabledtLabels.PurchaseIDColumn) = Global.System.Convert.DBNull
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Function IsQtyNull() As Boolean
      Return Me.IsNull(Me.tabledtLabels.QtyColumn)
    End Function

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Sub SetQtyNull()
      Me(Me.tabledtLabels.QtyColumn) = Global.System.Convert.DBNull
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Function IsBarcodeNull() As Boolean
      Return Me.IsNull(Me.tabledtLabels.BarcodeColumn)
    End Function

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Sub SetBarcodeNull()
      Me(Me.tabledtLabels.BarcodeColumn) = Global.System.Convert.DBNull
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Function IsSalePriceNull() As Boolean
      Return Me.IsNull(Me.tabledtLabels.SalePriceColumn)
    End Function

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Sub SetSalePriceNull()
      Me(Me.tabledtLabels.SalePriceColumn) = Global.System.Convert.DBNull
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Function IsModelNameNull() As Boolean
      Return Me.IsNull(Me.tabledtLabels.ModelNameColumn)
    End Function

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Sub SetModelNameNull()
      Me(Me.tabledtLabels.ModelNameColumn) = Global.System.Convert.DBNull
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Function IsSizeTitleNull() As Boolean
      Return Me.IsNull(Me.tabledtLabels.SizeTitleColumn)
    End Function

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Sub SetSizeTitleNull()
      Me(Me.tabledtLabels.SizeTitleColumn) = Global.System.Convert.DBNull
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Function IsColorNameNull() As Boolean
      Return Me.IsNull(Me.tabledtLabels.ColorNameColumn)
    End Function

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Sub SetColorNameNull()
      Me(Me.tabledtLabels.ColorNameColumn) = Global.System.Convert.DBNull
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Function IsSalePercentageNull() As Boolean
      Return Me.IsNull(Me.tabledtLabels.SalePercentageColumn)
    End Function

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Sub SetSalePercentageNull()
      Me(Me.tabledtLabels.SalePercentageColumn) = Global.System.Convert.DBNull
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Function IsCompanyNameNull() As Boolean
      Return Me.IsNull(Me.tabledtLabels.CompanyNameColumn)
    End Function

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Sub SetCompanyNameNull()
      Me(Me.tabledtLabels.CompanyNameColumn) = Global.System.Convert.DBNull
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Function IsBarcodeImageNull() As Boolean
      Return Me.IsNull(Me.tabledtLabels.BarcodeImageColumn)
    End Function

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Sub SetBarcodeImageNull()
      Me(Me.tabledtLabels.BarcodeImageColumn) = Global.System.Convert.DBNull
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Function IsRecIDNull() As Boolean
      Return Me.IsNull(Me.tabledtLabels.RecIDColumn)
    End Function

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Sub SetRecIDNull()
      Me(Me.tabledtLabels.RecIDColumn) = Global.System.Convert.DBNull
    End Sub
  End Class

  '''<summary>
  '''Row event argument class
  '''</summary>
  <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
  Public Class dtLabelsRowChangeEvent
    Inherits Global.System.EventArgs

    Private eventRow As dtLabelsRow

    Private eventAction As Global.System.Data.DataRowAction

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public Sub New(ByVal row As dtLabelsRow, ByVal action As Global.System.Data.DataRowAction)
      MyBase.New()
      Me.eventRow = row
      Me.eventAction = action
    End Sub

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public ReadOnly Property Row() As dtLabelsRow
      Get
        Return Me.eventRow
      End Get
    End Property

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")> _
    Public ReadOnly Property Action() As Global.System.Data.DataRowAction
      Get
        Return Me.eventAction
      End Get
    End Property
  End Class
End Class
